config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'html_pages#home'
  get '/about', to: 'html_pages#about'
  get '/contact', to: 'html_pages#contact'
  get '/help', to: 'html_pages#help'
  get '/signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :snapshots, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, :followed_id, presence: true
end

app/models/snapshot.rb
# frozen_string_literal: true

class Snapshot < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }

  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: 'Please upload a valid fule type(jpeg, gif, png).' },
                    size: { less_than: 5.megabytes,
                            message: '  Your image exceded 5MB.' }

  def display_image
    image.variant(resize_to_limit: [200, 200])
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :snapshots, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, :email, presence: true
  validates :name, length: { minimum: 1, maximum: 60 }
  validates :email, length: { minimum: 4, maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def feed
    Snapshot.where('user_id = ?', id)
    Snapshot.where('user_id IN (?) or user_id = ?', following_ids, id)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'Please log in'
    redirect_to login_path
  end
end

app/controllers/html_pages_controller.rb
# frozen_string_literal: true

class HtmlPagesController < ApplicationController
  def home
    if logged_in?
      @snapshot = current_user.snapshots.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help; end

  def about; end

  def contact; end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user, only: %i[create destroy]

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user_path(user)
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user_path(user)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  before_action :logged_in_user, only: %i[create destroy]
  before_action :correct_user, only: :destroy

  def create
    @snapshot = current_user.snapshots.build(snapshot_params)
    @snapshot.image.attach(params[:snapshot][:image])
    if @snapshot.save
      flash[:success] = 'Snapshot created'
      redirect_to root_path
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'html_pages/home'
    end
  end

  def destroy
    @snapshot.destroy
    flash[:success] = 'Snapshot has been delete'
    redirect_to request.referrer || root_path
  end

  private

  def correct_user
    @snapshot = current_user.snapshots.find_by(id: params[:id])
    redirect_to root_path if @snapshot.nil?
  end

  def snapshot_params
    params.require(:snapshot).permit(:content, :image)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :logged_in_user, only: %i[show index edit update destroy following followers]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @snapshots = @user.snapshots.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to Orbit'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to users_path
  end

  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    redirect_to root_path unless current_user?(@user)
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :passoword_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Orbit Feedback Application'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/html_pages_helper.rb
# frozen_string_literal: true

module HtmlPagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_path] || default)
    session.delete(:forwarding_path)
  end

  def store_location
    puts request
    session[:forwarding_path] = request.original_url if request.get?
  end

  def current_user?(user)
    user && user == current_user
  end
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/html_pages/about.html.erb
<% provide(:title, 'About')%>
<h1>About</h1>
<p>Find me in app/views/html_pages/home.html.erb</p>

app/views/html_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>Put your email for to send the message</p>

app/views/html_pages/help.html.erb
<% provide(:title, 'Help')%>
<h1>Help</h1>
<p>Find me in app/views/html_pages/help.html.erb</p>

app/views/html_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if logged_in? %>
<div class='snapshots-home'>
  <aside>
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= render 'shared/snapshot_form' %>
    </section>
  </aside>
  <div>
    <h3>Snapshot feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to Orbit</h1>
  <h2>
    This is a home pageof the Orbitapplication. You can find
    the codebasefot this application a
    <a href="https://github.com/CarlosEnrique103/orbit" target="blank">my github.</a>
  </h2>
  <%= link_to "Create an account ", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Orbit Feedback Application
  </small>
  <nav>
    <ul>
      <li> <%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Orbit Application", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
        <li> <%= link_to "Users", users_path %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<![if lt IE 9]-->
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min,js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <% flash.each do |message_type, message|%>
  <div class="alert alert-<%=message_type%>">
    <%= message %>
  </div>
  <% end %>
  <%= render 'layouts/header' %>
  <div class=" container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form container <%= pluralize(object.errors.count, "error") %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |message|%>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol>
  <%= render @feed_items %>
</ol>
<%= will_paginate @feed_items, params: { controller: :html_pages, action: :home } %>
<% end %>

app/views/shared/_snapshot_form.html.erb
<%= form_with( model: @snapshot , local: true) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.text_area :content, placeholder: 'Create a new snapshot...' %>
</div>
<span class="image">
  <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>
</span>
<%= f.submit 'Send', class: 'btn btn-primary' %>
<% end %>

<script type="text/javascript">
  let snapshot = document.getElementById("snapshot_image");
  snapshot.addEventListener('change', ({
    target
  }) => {
    let size_in_megabytes = target.files[0].size / 1024 / 1024;
    console.log(size_in_megabytes);
    if (size_in_megabytes > 5) {
      alert('Image cannot execed 5MB. Please choose a smaller file.');
    }
  })
</script>

app/views/shared/_stats.html.erb
<% if @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), user_path(current_user) %>
<h1><%= current_user.name %></h1>
<span><%= link_to "View my profile", user_path(current_user) %></span>
<span><%= pluralize(current_user.snapshots.count, 'snapshot') %></span>

app/views/snapshots/_snapshot.html.erb
<li id="snapshot-<%= snapshot.id %>">
  <%= link_to gravatar_for(snapshot.user), snapshot.user %>
  <div class="content">
    <span class="user"><%= link_to snapshot.user.name, snapshot.user %></span>
    <span class="content"><%= snapshot.content %></span>
    <%= image_tag snapshot.display_image if snapshot.image.attached? %>
    <span class="timestamp">
      Posted <%= time_ago_in_words(snapshot.created_at)%> ago.
      <% if current_user?(snapshot.user) %>
      <%= link_to 'Delete', snapshot_path(snapshot), method: :delete, data: { confirm: 'Are you sure?'} %>
      <% end %>
    </span>
  </div>
</li>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit 'Follow', class: 'btn btn-primary' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
  <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
  <% else %>
  <%= render 'follow' %>
  <% end %>
</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id), local: true, html: { method: :delete}) do |f| %>
<%= f.submit 'Unfollow', class: 'btn btn-danger' %>
<% end %>

app/views/users/_user.html.erb
 <li>
   <%= gravatar_for user %>
   <%= link_to user.name, user_path(user) %>
   <% if current_user.admin? && !current_user?(user) %>
   <%= link_to "Delete", user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %>
   <% end %>
 </li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit</h1>
<div class="container-form">
  <div>
    <%= gravatar_for @user %>
    <a href="https://gravatar.com/emails" target="_blank">change</a>
  </div>

  <%= form_with(model: @user, local: true) do |f|%>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email,  class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password,  class: 'form-control' %>

  <%= f.label :password_confirmation, 'Confirmation' %>
  <%= f.password_field :password_confirmation,  class: 'form-control' %>

  <%= f.submit 'Save changes', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Users</h1>

<%= will_paginate %>

<ul class="list-users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Signup') %>
<h1>Signup</h1>
<div class="container-form">
  <%= form_with(model: @user, local: true) do |f|%>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email,  class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password,  class: 'form-control' %>

  <%= f.label :password_confirmation, 'Confirmation' %>
  <%= f.password_field :password_confirmation,  class: 'form-control' %>

  <%= f.submit 'Create my account', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>

<div class="container-profile">
  <aside>
    <h1>
      <%= gravatar_for(@user) %>
      <%= @user.name %>
    </h1>
    <%= render 'shared/stats' %>
  </aside>
  <main>
    <%= render 'follow_form' if logged_in? %>
    <% if @user.snapshots.any? %>
    <h3>Snapshots <%= @user.snapshots.count %> </h3>
    <ol class="snapshots">
      <%= render @snapshots %>
    </ol>
    <%= will_paginate @snapshots %>
    <% end %>
  </main>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="use_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span>
        <%= link_to 'view my profile', @user %>
      </span>
      <span>
        <b>Snapshots: </b> <%= @user.snapshots.count %></b>
      </span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
      <div class="user_avatars">
        <% @users.each do |user| %>
        <%= link_to gravatar_for(user), user %>
        <% end %>
      </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
    <ul class="users follow">
      <%= render @users%>
    </ul>
    <%= will_paginate %>
    <% end%>
  </div>
</div>